# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [1]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/EduardoSSBispo/IA--Atividade-08--Redes--Neurais/main/diabetesAprendizado.csv'
base_Treinamento = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

ModuleNotFoundError: No module named 'pandas'

### Pré-processamento de Dados

In [ ]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

# Binarizador de rótulo

scaler = StandardScaler()
X_Train = np.array(base_Treinamento[:, 0 : 7])
X_Train_scaled = scaler.fit_transform(X_Train)

lb = preprocessing.LabelBinarizer()

Pregnancies = base_Treinamento[:,0]
Glucose = base_Treinamento[:,1]
BloodPressure = base_Treinamento[:,2]
SkinThickness = base_Treinamento[:,3]
Insulin = base_Treinamento[:,4]
BMI = base_Treinamento[:,5]
DiabetesPedigreeFunction = base_Treinamento[:,6]
Age = base_Treinamento[:,7]

classes = base_Treinamento[:,8]

#Concatenação de Atributos (Colunas)
atributos_norm = np.column_stack((Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 

### Treinamento do Neurônio Perceptron

In [2]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

ModuleNotFoundError: No module named 'sklearn'

### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [ ]:
Luiz = [[0,120,29,19,46.7,0.798, 27, 1]]
print("Luiz", modelo.predict(Luiz))
Laura = [[3,88,29,0,28.1,0.300, 49, 0]]
print("Laura", modelo.predict(Laura))

Luiz [1.]
Laura [1.]


### Predição a partir de base de dados (.csv)

In [ ]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/EduardoSSBispo/IA--Atividade-08--Redes--Neurais/main/diabetesTeste.csv'
base_Testes = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:7])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[2.00e+00 1.30e+02 9.60e+01 0.00e+00 0.00e+00 2.26e+01 2.68e-01 2.10e+01
  0.00e+00]
 [1.00e+01 1.33e+02 6.80e+01 0.00e+00 0.00e+00 2.70e+01 2.45e-01 3.60e+01
  0.00e+00]
 [6.00e+00 1.94e+02 7.80e+01 0.00e+00 0.00e+00 2.35e+01 1.29e-01 5.90e+01
  1.00e+00]
 [4.00e+00 1.27e+02 8.80e+01 1.10e+01 1.55e+02 3.45e+01 5.98e-01 2.80e+01
  0.00e+00]
 [1.20e+01 1.00e+02 8.40e+01 3.30e+01 1.05e+02 3.00e+01 4.88e-01 4.60e+01
  0.00e+00]
 [4.00e+00 9.10e+01 7.00e+01 3.20e+01 8.80e+01 3.31e+01 4.46e-01 2.20e+01
  0.00e+00]
 [5.00e+00 1.37e+02 1.08e+02 0.00e+00 0.00e+00 4.88e+01 2.27e-01 3.70e+01
  1.00e+00]]
---------------------------------
Atributos de Entrada
---------------------------------
[[2.00e+00 1.30e+02 9.60e+01 0.00e+00 0.00e+00 2.26e+01 2.68e-01]
 [1.00e+01 1.33e+02 6.80e+01 0.00e+00 0.00e+00 2.70e+01 2.45e-01]
 [6.00e+00 1.94e+02 7.80e+01 0.00e+00 0.00e+00 2.35e+01 1.29e-01]
 [4.00e+00 1.27e+02 8.8

### Pré-processamento de Dados

In [ ]:
import numpy as np
from sklearn import preprocessing

lb = preprocessing.LabelBinarizer()

Pregnancies = base_Treinamento[:,0]
Glucose = base_Treinamento[:,1]
BloodPressure = base_Treinamento[:,2]
SkinThickness = base_Treinamento[:,3]
Insulin = base_Treinamento[:,4]
BMI = base_Treinamento[:,5]
DiabetesPedigreeFunction = base_Treinamento[:,6]
Age = base_Treinamento[:,7]

#Concatenação de Atributos (Colunas)
atributos_norm = np.column_stack((Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


### Predição da Base

In [ ]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

### Retorno aos valores Categóricos

In [ ]:
import numpy as np
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

Pregnancies = base_Treinamento[:,0]
Glucose = base_Treinamento[:,1]
BloodPressure = base_Treinamento[:,2]
SkinThickness = base_Treinamento[:,3]
Insulin = base_Treinamento[:,4]
BMI = base_Treinamento[:,5]
DiabetesPedigreeFunction = base_Treinamento[:,6]
Age = base_Treinamento[:,7]

classes = base_Treinamento[:,8]

#Concatenação de Atributos (Colunas)
atributos_cat = np.column_stack((Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_cat)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
